Duet3D/PanelDueFirmware

src/Strings.hpp

This is a first draft of a file translation in french. I can shorten some of the strings if needed.

First pass on a french translation

---

.cproject
src/Configuration.hpp
src/DisplaySize.hpp
src/Hardware/UTFT.cpp
src/Hardware/UTFT.hpp
src/Hardware/memorysaver.h

Added support for 7" displays using CPLD drivers

Added Support For 7" CPLD

---

src/Strings.hpp

I tried to translate the strings with words one would expect from a machine in certain cases.

Spanish strings

---

Readme.md

I'm not using windows, so i tried to add the splash screen using linux.
Maybe it's useful for others too.

Added linux instruction to append splash screen

---

.gitignore
src/UserInterface.cpp

add axis coordinates to MovePopup and PrintTab

---

.cproject
.gitignore

* Tools is now excluded from Builds => No need to remove this folder before compilation
* added OEM* and Release-* to .gitignore

excluded Tools from build, git ignore improvements

---

src/Strings.hpp

Hi,
I added the Italian translation.
Hope it's useful :)

Added italian translation

---

Tools/list-locales/list-locales.cpp
src/Fonts/glcd19x21.cpp
src/Fonts/glcd28x32.cpp
src/Hardware/UTFT.cpp
src/UI/Events.hpp
src/UI/Strings.hpp
src/UI/UserInterface.cpp

rename print to status

---

.gitignore
src/Hardware/SerialIo.cpp
src/Hardware/SerialIo.hpp
src/ObjectModel/PrinterStatus.hpp
src/PanelDue.cpp
src/PanelDue.hpp
src/RequestTimer.cpp
src/UI/UserInterface.cpp

Improve seqs requests with errors

---

src/ObjectModel/Axis.cpp
src/ObjectModel/Axis.hpp
src/ObjectModel/BedOrChamber.cpp
src/ObjectModel/BedOrChamber.hpp
src/ObjectModel/ListHelpers.hpp
src/ObjectModel/Tool.cpp
src/ObjectModel/Tool.hpp

ObjectModel: replaced usage of inplace_function with function_ref

---

src/FileManager.cpp
src/PanelDue.cpp

Fix normal polling interval

---

src/PanelDue.cpp

Log json parsing error as warning

---

src/FlashData.cpp
src/FlashData.hpp
src/Hardware/Backlight.hpp
src/UI/DisplaySize.hpp
src/UI/UserInterface.cpp
src/Version.hpp

Prepare release

---

src/UI/UserInterface.cpp

UserInterface: fixed logic test if prefixes are stripped

---

src/Hardware/SerialIo.cpp
src/Hardware/SerialIo.hpp
src/PanelDue.cpp

Improve debugging interface

---

src/PanelDue.cpp
src/UI/Display.hpp
src/UI/Popup.hpp
src/UI/UserInterface.cpp
src/UI/UserInterface.hpp

M291 S2 and S3 makes devices unresponsive during active screensaver

---

src/PanelDue.cpp

Job duration parse from object model

---

src/PanelDue.cpp
src/UI/UserInterface.cpp
src/UI/UserInterface.hpp

Fix displaying of standby temp row

---

src/Hardware/SerialIo.cpp
src/PanelDue.cpp

Fix json warnings during startup

---

.github/ISSUE_TEMPLATE/BugReport.yml
.github/ISSUE_TEMPLATE/FeatureRequest.yml
.github/ISSUE_TEMPLATE/Misc.yml

Gitlab simplify issue templates

---

Tools/list-locales/Makefile
Tools/list-locales/list-locales.cpp
src/ObjectModel/PrinterStatus.hpp
src/UI/Strings.hpp
src/UI/UserInterface.cpp

PrinterStatus: added new state cancelling

---

src/PanelDue.cpp
src/PanelDue.hpp
src/UI/UserInterface.cpp
src/UI/UserInterface.hpp

Activate screen on message

---

src/PanelDue.cpp

Fix slow polling interval

---

src/PanelDue.cpp
src/UI/UserInterface.cpp

Fix macro buttons control tab

---

src/Hardware/Backlight.cpp
src/Hardware/Backlight.hpp
src/PanelDue.cpp
src/PanelDue.hpp
src/UI/UserInterface.cpp

Fix dim handling

---

src/Hardware/UTouch.cpp
src/Hardware/UTouch.hpp
src/PanelDue.cpp

Added button pressed repeat handling

---

.cproject
.settings/language.settings.xml
src/Hardware/Buzzer.cpp
src/Version.hpp

Clsos #191.
Added code to support new integrated displays with MP3302 backlight inverter

Added support for newer integrated displays with MP3302 backlight chip

---

src/PanelDue.cpp

PanelDue: moved nvdata init to an earlier stage before first access

---

src/PanelDue.cpp

PanelDue: added generic button release handling

---

src/UI/Strings.hpp

Cleanup translations

---

src/Configuration.hpp

Config: enabled cyrillic alphabet langues by default

---

src/PanelDue.cpp

first repeat interval is 250ms and any following is 100ms
Closes 194.

PanelDue: fixed touch press repeat state machine

---

src/PanelDue.cpp

PanelDue: fix mounting other volumes

---

src/UI/Strings.hpp

Strings: updated french translation

---

src/UI/Strings.hpp

Strings: updated czech translation

---

src/UI/Strings.hpp

Strings: fixed spanish translation

---

src/UI/UserInterface.cpp

UI: added additional extrusion speeds to extrusion dialog

---

CMakeLists.txt
src/UI/Alert.hpp
src/UI/Events.hpp
src/UI/Popup.cpp
src/UI/Popup.hpp
src/UI/UserInterface.cpp
src/UI/UserInterface.hpp
src/UI/UserInterfaceConstants.hpp

Add more axis to movement popup

---

src/UI/Display.cpp

Display: fixed TextButtonWithLabel y-offset correction

---

src/UI/ColourSchemes.cpp

ColourScheme: added border colour to dark theme 2's popups

---

src/Hardware/SerialIo.cpp
src/Hardware/SerialIo.hpp
src/PanelDue.cpp

Improve warning messages

---

CMakeLists.txt

build: added support for ccache

---

src/UI/Strings.hpp
src/UI/UserInterface.cpp

Integrate polish translation

---

src/UI/Popup.cpp

Popup: optimized mapping of drive letters to buttons in jog dialog

---

src/UI/UserInterface.cpp

UI: added special case handling for lower case drive letters

---

src/UI/Popup.cpp
src/UI/Popup.hpp
src/UI/UserInterface.cpp

Fix toggling drive letter buttons in jog dialog

---

src/UI/UserInterface.cpp
src/UI/UserInterface.hpp

Fix baby step button handling

---

src/UI/UserInterface.cpp

UI: hide babystep button if not in printing or simulating state

---

src/PanelDue.cpp
src/UI/UserInterface.cpp
src/UI/UserInterfaceConstants.hpp

display baby stepping option at all times

---

src/UI/UserInterface.cpp
src/UI/UserInterfaceConstants.hpp

UI: in status tab show resume and cancel button when print is paused

---

src/FileManager.cpp
src/UI/Strings.hpp
src/UI/UserInterface.cpp
src/UI/UserInterface.hpp

report no files found in file popup

---

src/UI/UserInterface.cpp
src/Version.hpp

316 menues not displayed properly

---

src/UI/Popup.cpp

Popup: added alert mode choices to allow displaying of cancel button

---

src/Debug.hpp
src/FlashData.cpp
src/FlashData.hpp
src/Hardware/FlashStorage.cpp
src/PanelDue.cpp
src/UI/Events.hpp
src/UI/MessageLog.cpp
src/UI/MessageLog.hpp
src/UI/Strings.hpp
src/UI/UserInterface.cpp

MessageLog: introduced loglevel normal and verbose

---

src/UI/Strings.hpp
src/UI/UserInterface.cpp

281 add dutch translation

---

src/UI/Strings.hpp
src/UI/UserInterface.cpp

317 two digits for the display of x and y coordinates

---

src/Hardware/SerialIo.cpp

SerialIo: increased nesting and max field id length

---

src/PanelDue.cpp
src/UI/UserInterface.cpp
src/UI/UserInterface.hpp

feat: add a popup showing "Updating firmware"
